// Display translations only. Retrieval keeps the original committed query ID and text.
export const englishQuestionLabels: Record<string, string> = {
  q01: "What is the late-payment interest rate for consumer loans?",
  q02: "What is the maximum term of a consumer loan?",
  q03: "What down payment is required for a mortgage?",
  q04: "What documents are required for a consumer loan?",
  q05: "What is the minimum score for automatic approval?",
  q06: "What happens when a person appears on PEP lists?",
  q07: "What methods does identity verification use?",
  q08: "What facial-similarity threshold confirms identity?",
  q09: "Which identity documents are accepted?",
  q10: "How is collection strategy segmented by overdue days?",
  q11: "What is the maximum consumer-loan amount?",
  q12: "How is a credit-card limit calculated?",
  q13: "What requirements and score allow a consumer loan without review?",
  q14: "When does identity verification require manual review?",
  q15: "What is the maximum consumer-loan amount, and when is a credit committee required?",
  q16: "What signals indicate application fraud?",
  q17: "What is the maximum client exposure relative to regulatory capital?",
  q18: "Compare the maximum terms of consumer loans and mortgages.",
  q19: "What interest rate, maximum term and maximum amount apply to a consumer loan?",
  q20: "How many customers were approved last month?",
  q21: "Who is the organization's marketing director?",
  q22: "How do you make mushroom risotto?",
  q23: "What is the minimum term for large consumer loans?",
  q24: "What collection strategy applies to a business customer owing over ten million?",
};
